language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIAIPHIMQ6QTIUFUIXA
  secret_access_key:
    secure: CBK6tSHILxuVycKAZGhTN2bmlcfwToqDRByhKlKQztaUER3U7hvia7L8IqHoritO/bAxvgvXOZCDv3Yb+bSGdqGmRIeVQIkPUFKY3ITu5kwA0qZEQ+4bEQEC5vosqu4rssSV7bVr/d0VNY8C+msD3GRIOA2a0s3x52qm0fM/8cSE92mwPeVkeuphS9eTHcWrMCr12iJzq6ox6c9mZcdOGn54INXhJuD2Dqiw/guoNcYuo4rtolcpqdVfF37CnNN1Ov5cSfQwRda70FSBlFnqEdIeLScumPPF9SaNXkuuDQ3riLFydMnHFQdFMAbdo03JZZ0ezpAYn2jHTHLzoI0cRFCE+WEE6Z92c/nPud8dQmLuQKnyEZyHDKmjjBFUycAEwdYu5ogYVQ+839+Sa/3q+Se+KbVclNKbdJvSujzEKt5LIf7e1askAN+152WSMdZ+klKObuaMmibTwFN4bnzDdcMqe06ccgbdtPb1sloBUMi8XJHLjOoWS1ibzsfFIh/0oWLuZ2Z6fOVvhVvWypkm/IuhUVcRKF5I7yy2mLtzaf62Tj1A+sycrEVLcRLAucnyT0cur+cfyZ2BpiN02Vsys+pPuOiFM0rn/j0iPWPHmH2pj3Ne1F3FeI7tmQXwSTOlUXoRPcyRTtUtI1c49C/DHcFP7gqOIYtKbXxuW6susNQ=
  bucket: georgify.org
