language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: "AKIAIPHIMQ6QTIUFUIXA"
  secret_access_key:
    secure: "BzPfFus+y0A4RRPeWYp+Nipv7pfR/gCM9XsRxTwNQ4z1llMIgWwqW2EW2/TqU7Esu7k89PhBuc2pFDt4Ci20G5Fb1UWD/9R+tBJa8J/5yG/Z+RVK4APnslZK2otjQm9D3z0fMrckV2QhsP3WfqKIljH4EUX5zOxDFOPBtgy8Yxc4Ku7X9J5dqbxiWa/xXTqWB0a1bInIIUHXz9ZIAQaTT5SVBMsfqUCZg+ykzTJfeUl7pT255V7Tu+jlte4fLDdeDNvBvoiu6XJ5eOg29jfdhs4FQowKZ8jv61WEb6FJ5GsgWHdZwqWAhaIy1Q3rT650wDBCR/w/CUuWpdUwqEK6CUNxzKB4B3PaoKWJ7lH8b6uUa9ijpTkMuAmAYnYEuPVLeFe/St1KxCVqyqUGzXVGSQs101uQyltdiwiJC+OMEeRySyVIqpSwC7jUJNyFl6vaMMOs85GgK5xet49Up0CQwQCFWHHBOs/rhK7qwmfyH3hGGuUq7xocjbZfgS07fEKrDOg3gVz5zPc52nVnXbNAh5aEHAhWIquc28JGq8z6o+771ALM8DiXvvt9yqu/DPmj1DVC6jNXHsoGU6Li/F+cS5ihvxHcpzoXhmcbbSZv55I+XWir4czyksDCXmLXp2nGGdoO2ldlDCuoajBI/sYTl0fpxqmhS9tNAa1YcB2XPac="
  bucket: georgify.org
