language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJP5ZY6YD2DAFZSQA
  secret_access_key:
    secure: Rb74JHocyDGj6k71zKklOty4B+sS4yPkNKiEw/U8AFpS6UsjPwd1438zhOKhWQZoBQqXYt5i9Gan7QYC6MtlzVAcPB22GeO+pkP05UOeamHJ2peFaMYwOebkWs0zY19p8MX85o3v9MPc5fL/bcpCCywacM5jJ2UpKXI2mh5DQ4TfxE0KSCtLFfzzm4l3C5Ba2EtZYvbOg6Qy9foRgdpg8S0AYssoGIv45TDbRiuRrJ2jjLq+DyNYWrUrlIPaq0UoGi1ZhtJP/rWrpuwvGaActeWEgJ7fkaP70+oYs4wind7qg7a43I9L+Sf5RexnVhdfIRmJR+flXNGuUka5OxO91rFalvCWqyNxX1CXJTNU4JFGxT5U4pEhB/sTrGzlF7GqqP4CqhJ7fPx+F1xxxEgzWmzdttkjwRWbmbqymi2x8IxihKv9Ns6VLOF3MFeSqVyxucEW62zef4gmsY12F/SBRkc5dzWnQ/Q43VKVgndl+munZJaj1Bmf7sF0JtpRcyEOV0TV8KNSQbd3Fv9HN9pdh7gjTa58/Vx3JTuGPVmVX86ECNrifyuLNGPpGkU+mF/CScahAxCcG5dB40K7VPVbZsCfj5DTM+M1gd/xnTIgG0QGHq0hLmyphpCc0rKzddo5p6Ci8IB9kTqeQqOm17w4P2SHw/41ZWNHFHaYFKp/ntY=
  bucket: georgify.org
