language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: "AKIAIPHIMQ6QTIUFUIXA"
  secret_access_key:
    secure: rf80Mdfp0fXa56hN6t6gWlPEZ+d0jee9gK9pUrNCgQebNic+oTZlsjQkDzyybmaAy6juEuNieKbyJDAOMDmFPrA0JwPvYwT1UWZM27iACLiQSzjRuxNY1F0idcPSmgnc2sPlFMUJcP7bgEDBmm35TFsqIn+2zBGQQiB1Glix94ye9qi+62iT4UnCxZw2Tf51c0x6IjN2Vxlq2iv0VbPW1wybukP1BNXzo10AGEUtjfkfxKAlKlFtuGwGWhyRslijEV1pDEOVf6Bf4pre/IvPQubup1hhOdxxLE9QzrPxonkpKIQtnA0N0RpJJlZqJ5DbOTyATJPy4CUmEj1EgR4QQVivVx6EUEDNe628TDiRhiEl6ZXGB2+3fnRn+1UvWcXnAlo2vCF9VGvWtMI2QEJ3kC7hXhTlcHqRYvgOWfC0TeMWavhDCU62yRJm1+jOrJ7JueeeepWv4p5HF0+O3KPdSATPQevvrSHYLZm4F3flbqe/+xShDxTWg2Ayhb4Ef+D8yZob9Iq//E7KyfOkQkyZPYSuM6E+bH2kZjTKPmKn5YT5Q00n55G/U5h0lT+4ZPxe13GhcmqvUzYQs8kylZ4jMk3AwtamuOFyU+VsQjV/w3ioaT5v6vpoWGV4tp1KzfNcyPU6aLPprErsAdXx1kVDF44a9hkgnMDpPgJO3azH8QE=
  bucket: georgify.org
